//! Icons: a small owned sprite.
//!
//! Blender gives every editor an icon and shows it in the header's editor
//! selector; the old immersion did the same. A name alone makes a header read
//! as a form, and makes a menu of twelve editors a wall of words — an icon is
//! what lets you find the Runs area without reading.
//!
//! The whole Tabler outline set (MIT) is vendored as path data — 5,130 glyphs,
//! 1.2 MB, generated by `scripts/build-icons.ts`. It began as a dozen
//! hand-picked ones, which is fine until a host wants an icon for an editor of
//! its own and has to come here to add it. All of them costs less than the
//! diff renderer and means an editor names any Tabler icon and gets it.
//!
//! Outline only: every glyph is stroked in `currentColor`, so it takes the
//! text colour wherever it is placed, and the filled set would double the size
//! to supply a second look nothing here asks for. One 24x24 grid throughout.

/// `(name, svg body)`. The body is whatever goes inside `<svg>` — strokes,
/// not fills, so one glyph works on any background the theme has.
/// The vendored set, as path data keyed by name. 1.2 MB of JSON parsed once,
/// on the first icon anyone asks for — a `OnceLock` rather than a lazy static
/// so the cost is paid by whoever needs it and never by a host that draws no
/// icons at all.
static SHEET: &str = include_str!("../vendor/icons/tabler-outline.json");

fn sheet() -> &'static std::collections::HashMap<String, String> {
    static PARSED: std::sync::OnceLock<std::collections::HashMap<String, String>> =
        std::sync::OnceLock::new();
    PARSED.get_or_init(|| serde_json::from_str(SHEET).unwrap_or_default())
}

/// One icon as an inline `<svg>`, or an empty string for a name nobody drew.
/// Empty rather than a placeholder: a missing icon should leave a header
/// looking ordinary, not decorated with a question mark.
pub fn icon(name: &str) -> String {
    let Some(body) = sheet().get(name) else {
        return String::new();
    };
    format!(
        r#"<svg class="im-icon" viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{body}</svg>"#
    )
}

/// Whether a glyph exists, for callers that lay out differently without one.
pub fn has_icon(name: &str) -> bool {
    sheet().contains_key(name)
}

/// Every name in the set, sorted. For a host building a picker, and for the
/// tests that hold declared icons against what exists.
pub fn icon_names() -> Vec<&'static str> {
    let mut names: Vec<&str> = sheet().keys().map(String::as_str).collect();
    names.sort_unstable();
    names
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_icon_is_inline_svg_that_inherits_its_colour() {
        let svg = icon("chart-line");
        assert!(svg.starts_with("<svg"), "{svg}");
        assert!(
            svg.contains("currentColor"),
            "an icon takes the text colour"
        );
        assert!(
            svg.contains("viewBox=\"0 0 24 24\""),
            "one grid for all of them"
        );
        assert!(svg.contains("<path"), "and has something to draw");
    }

    #[test]
    fn a_name_nobody_drew_is_nothing_rather_than_a_placeholder() {
        assert_eq!(icon("no-such-icon"), "");
        assert!(!has_icon("no-such-icon"));
        assert!(has_icon("folder"));
    }

    #[test]
    fn the_whole_outline_set_is_vendored() {
        // Not a handful of hand-picked glyphs any more: a host naming any
        // Tabler outline icon for an editor of its own gets it.
        let names = icon_names();
        assert!(names.len() > 5_000, "only {} icons vendored", names.len());
        assert!(
            names.windows(2).all(|w| w[0] < w[1]),
            "names are sorted and unique"
        );
        // A sample across the alphabet, drawable and stroked.
        for n in ["adjustments", "flame", "rocket", "zoom-in"] {
            let svg = icon(n);
            assert!(
                svg.contains("<path") || svg.contains("<circle"),
                "{n} draws nothing"
            );
            assert!(
                svg.contains("currentColor"),
                "{n} does not take the text colour"
            );
        }
    }
}
